export const FETCH_USER = "FETCH_USER";
export const SELECT_USER = "SELECT_USER";

export const VIEW_POST = "VIEW_POST";
export const FETCH_POST = "FETCH_POST";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const FETCH_POST_COMMENT = "FETCH_POST_COMMENT";
export const FETCHING_POST_COMMENT = "FETCHING_POST_COMMENT";

export const CLEAR_USER_POST = "CLEAR_USER_POST";
export const FETCH_USER_POST = "FETCH_USER_POST";
export const CREATING_USER_POST = "CREATING_USER_POST";
export const FETCHING_USER_POST = "FETCHING_USER_POST";
